In [1]:
#1.导入numpy库并简写为 np
import numpy as np

In [4]:
#2.打印numpy的版本和配置说明
print(np.__version__)
np.show_config()

1.12.1
blas_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Users/yang9/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/yang9/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Users/yang9/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/yang9/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Users/yang9/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/yang9/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Users/y

In [5]:
#3.创建一个长度为10的空向量
z=np.zeros(10)
print(z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [6]:
#4.如何找到任何一个数组的内存大小？
z= np.zeros((10,10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


In [8]:
#5. 如何从命令行得到numpy中add函数的说明文档?
np.info(np.add)

add(x1, x2[, out])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).

Returns
-------
add : ndarray or scalar
    The sum of `x1` and `x2`, element-wise.  Returns a scalar if
    both  `x1` and `x2` are scalars.

Notes
-----
Equivalent to `x1` + `x2` in terms of array broadcasting.

Examples
--------
>>> np.add(1.0, 4.0)
5.0
>>> x1 = np.arange(9.0).reshape((3, 3))
>>> x2 = np.arange(3.0)
>>> np.add(x1, x2)
array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])


In [9]:
#6. 创建一个长度为10并且除了第五个值为1的空向量 
z=np.zeros(10)
z[4]=1
print(z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [11]:
#7. 创建一个值域范围从10到49的向量
z=np.arange(10,49)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [12]:
#8. 反转一个向量(第一个元素变为最后一个)
z=np.arange(10)
z=z[::-1]
print(z)

[9 8 7 6 5 4 3 2 1 0]


In [13]:
#9. 创建一个 3x3 并且值从0到8的矩阵
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
#10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [17]:
#11.创建一个 3x3 的单位矩阵
z=np.eye(3)
print(z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [19]:
#12.创建一个 3x3x3的随机数组
z=np.random.random((3,3,3))
print(z)

[[[ 0.02932407  0.33057869  0.1491679 ]
  [ 0.45293986  0.27716907  0.15170569]
  [ 0.70486399  0.0748491   0.83606562]]

 [[ 0.71822539  0.44417926  0.54920818]
  [ 0.05685114  0.98292224  0.91352717]
  [ 0.89700412  0.01790583  0.30894787]]

 [[ 0.1560267   0.29482776  0.79231776]
  [ 0.10502396  0.20934423  0.74298386]
  [ 0.00759396  0.9592899   0.48017779]]]


In [22]:
#13. 创建一个 10x10 的随机数组并找到它的最大值和最小值 
z=np.random.random((10,10))
zmax,zmin=z.max(),z.min()
print(zmax,zmin)

0.988641129908 6.83500020958e-05


In [23]:
#14. 创建一个长度为30的随机向量并找到它的平均值
z=np.random.random(30)
m=z.mean()
print(m)

0.488977082583


In [24]:
#15. 创建一个二维数组，其中边界值为1，其余值为0
z=np.ones((10,10))
z[1:-1,1:-1]=0
print(z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [26]:
#16. 对于一个存在在数组，如何添加一个用0填充的边界?
z=np.ones((5,5))
z=np.pad(z,pad_width=1,mode='constant',constant_values=0)
print(z)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [28]:
#17. 以下表达式运行的结果分别是什么?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [29]:
#18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置
z= np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [30]:
#19. 创建一个8x8 的矩阵，并且设置成棋盘样式
z=np.zeros((8,8),dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [31]:
#20.考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [32]:
#21.用tile函数去创建一个 8x8的棋盘样式矩阵
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [3]:
#22. 对一个5x5的随机矩阵做归一化
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[ 0.55400745  0.6066629   0.34897594  0.52205765  0.92396622]
 [ 0.20723694  0.77432533  0.78768336  0.2354423   0.73946455]
 [ 0.          0.26415104  0.37229725  0.47943471  0.95027384]
 [ 0.73238658  0.44075942  1.          0.79998958  0.9767169 ]
 [ 0.10460511  0.58473518  0.08888881  0.19909301  0.12268559]]


In [2]:
#23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？
color = np.dtype([("r", np.ubyte, 1),
                   ("g", np.ubyte, 1),
                   ("b", np.ubyte, 1),
                   ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [3]:
#24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


In [4]:
#25. 给定一个一维数组，对其在3到8之间的所有元素取反
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [5]:
#26. 下面脚本运行后的结果是什么? 
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [9]:
#27. 考虑一个整数向量Z,下列表达合法的是哪个?
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1


array([  0.,   1.,   2.,   3.,  -4.,  -5.,  -6.,  -7.,  -8.,   9.,  10.])

In [10]:
#28. 下列表达式的结果分别是什么?
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[ -2.14748365e+09]


C:\Users\yang9\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
C:\Users\yang9\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [11]:
#29. 如何从零位对浮点数组做舍入 ?
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ -2.   9.   4. -10.   2.   3.  -5.   1.  -5.  -1.]


In [12]:
#30. 如何找到两个数组中的共同元素?
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 5 7 8]


In [18]:
#31. 如何忽略所有的 numpy 警告(尽管不建议这么做)
/# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

SyntaxError: invalid syntax (<ipython-input-18-55f822eb5718>, line 8)

In [19]:
#32. 下面的表达式是正确的吗? 
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\yang9\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

In [20]:
#33. 如何得到昨天，今天，明天的日期?
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-21
Today is 2019-06-22
Tomorrow is 2019-06-23


In [21]:
#34. 如何得到所有与2016年7月对应的日期？
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [22]:
#35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)? 
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [25]:
#36. 用五种不同的方法去提取一个随机数组的整数部分
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[ 2.  6.  7.  8.  0.  3.  3.  0.  8.  7.]
[ 2.  6.  7.  8.  0.  3.  3.  0.  8.  7.]
[ 2.  6.  7.  8.  0.  3.  3.  0.  8.  7.]
[2 6 7 8 0 3 3 0 8 7]
[ 2.  6.  7.  8.  0.  3.  3.  0.  8.  7.]


In [26]:
#37. 创建一个5x5的矩阵，其中每行的数值范围从0到4
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


In [28]:
#38. 通过考虑一个可生成10个整数的函数，来构建一个数组
def generate():
     for x in range(10):
         yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [29]:
#39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


In [30]:
#40. 创建一个长度为10的随机向量，并将其排序 
Z = np.random.random(10)
Z.sort()
print (Z)

[ 0.01217533  0.17408195  0.18120922  0.36937197  0.40916964  0.43730173
  0.46094365  0.67828316  0.87500142  0.99767012]


In [31]:
#41.对于一个小数组，如何用比 np.sum更快的方式对其求和？
Z = np.arange(10)
np.add.reduce(Z)

45

In [32]:
#42. 对于两个随机数组A和B，检查它们是否相等
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [33]:
#43. 创建一个只读数组(read-only) 
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [34]:
#44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[ 0.18378397  0.91659276  0.92718577  0.40732572  0.8225168   0.4771299
  0.42527281  0.57811115  1.03109864  1.03585818]
[ 0.37231336  0.97653588  0.7247345   0.36080173  1.39945564  0.42382307
  1.09466241  0.31163747  1.23257621  0.70544029]


In [35]:
#45. 创建一个长度为10的向量，并将向量中最大值替换为1 
Z = np.random.random(10)
Z[Z.argmax()] = 0
print (Z)

[ 0.38796315  0.50954974  0.0361664   0.07350585  0.          0.27479469
  0.58322493  0.50711211  0.32796137  0.20309779]


In [36]:
#46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                              np.linspace(0,1,5))
print(Z)

[[( 0.  ,  0.  ) ( 0.25,  0.  ) ( 0.5 ,  0.  ) ( 0.75,  0.  )
  ( 1.  ,  0.  )]
 [( 0.  ,  0.25) ( 0.25,  0.25) ( 0.5 ,  0.25) ( 0.75,  0.25)
  ( 1.  ,  0.25)]
 [( 0.  ,  0.5 ) ( 0.25,  0.5 ) ( 0.5 ,  0.5 ) ( 0.75,  0.5 )
  ( 1.  ,  0.5 )]
 [( 0.  ,  0.75) ( 0.25,  0.75) ( 0.5 ,  0.75) ( 0.75,  0.75)
  ( 1.  ,  0.75)]
 [( 0.  ,  1.  ) ( 0.25,  1.  ) ( 0.5 ,  1.  ) ( 0.75,  1.  )
  ( 1.  ,  1.  )]]


In [37]:
#47. 给定两个数组X和Y，构造Cauchy矩阵C 
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.16363712


In [38]:
#48. 打印每个numpy标量类型的最小值和最大值？
for dtype in [np.int8, np.int32, np.int64]:
     print(np.iinfo(dtype).min)
     print(np.iinfo(dtype).max)

# for dtype in [np.float32, np.float64]:
     print(np.finfo(dtype).min)
     print(np.finfo(dtype).max)
     print(np.finfo(dtype).eps)

-128
127


ValueError: data type <class 'numpy.int8'> not inexact

In [39]:
#49. 如何打印一个数组中的所有数值?
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 

In [40]:
#50. 给定标量时，如何找到数组中最接近标量的值？
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

59


In [41]:
#51. 创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print (Z)

[(( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))]


In [42]:
#52. 对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[ 0.          0.43447266  0.4643809   0.28052766  0.54999685  0.46735667
   0.17361385  0.55560274  0.46695993  0.09462784]
 [ 0.43447266  0.          0.47662995  0.6899764   0.23635243  0.65606177
   0.54570768  0.81980696  0.13153796  0.51305394]
 [ 0.4643809   0.47662995  0.          0.5207531   0.35287761  0.23593357
   0.39918944  0.41728794  0.59998563  0.55052919]
 [ 0.28052766  0.6899764   0.5207531   0.          0.7456183   0.38580784
   0.1493077   0.37489875  0.74158222  0.26088255]
 [ 0.54999685  0.23635243  0.35287761  0.7456183   0.          0.57972712
   0.59707605  0.76002971  0.36146736  0.64260253]
 [ 0.46735667  0.65606177  0.23593357  0.38580784  0.57972712  0.
   0.32498184  0.18164988  0.76322471  0.52604647]
 [ 0.17361385  0.54570768  0.39918944  0.1493077   0.59707605  0.32498184
   0.          0.38605566  0.60687941  0.20576273]
 [ 0.55560274  0.81980696  0.41728794  0.37489875  0.76002971  0.18164988
   0.38605566  0.          0.91783976  0.5887352 ]
 [ 0.466

In [43]:
#53. 如何将32位的浮点数(float)转换为对应的整数
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [44]:
#54. 如何读取以下文件? 
np.genfromtxt

<function numpy.lib.npyio.genfromtxt>

In [45]:
#55. 对于numpy数组，enumerate的等价操作是什么？
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[ 0.36787944  0.44822088  0.51979489  0.57375342  0.60279818  0.60279818
   0.57375342  0.51979489  0.44822088  0.36787944]
 [ 0.44822088  0.54610814  0.63331324  0.69905581  0.73444367  0.73444367
   0.69905581  0.63331324  0.54610814  0.44822088]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [

In [46]:
#57. 对一个二维数组，如何在其内部随机放置p个元素? 
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [47]:
#58. 减去一个矩阵中的每一行的平均值
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.08255311 -0.162891    0.05023367  0.3599708   0.24998278 -0.22770007
  -0.10911675 -0.20327642  0.04509223  0.08025787]
 [ 0.02495776 -0.24077373 -0.14160686  0.18588642  0.06460197  0.17777707
  -0.09605683 -0.12035499  0.02850592  0.11706327]
 [-0.08261936 -0.3542172   0.25732879 -0.06620709  0.39255943 -0.39037282
  -0.21216822 -0.24063746  0.28065542  0.41567851]
 [ 0.00137853  0.04256    -0.43816478 -0.38439422  0.3165866   0.13917409
   0.21173948  0.24199149 -0.42447026  0.29359906]
 [ 0.11228908  0.21461986  0.22938605 -0.11786316  0.32601681 -0.37256498
  -0.21413804 -0.28249758 -0.44676113  0.55151309]]


In [48]:
#59. 如何通过第n列对一个数组进行排序?
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[0 0 8]
 [4 9 4]
 [9 8 9]]
[[0 0 8]
 [9 8 9]
 [4 9 4]]


In [49]:
#60. 如何检查一个二维数组是否有空列？
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

True


In [50]:
#61. 从数组中的给定值中找出最近的值
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.513547387725


In [51]:
#62. 如何用迭代器(iterator)计算两个分别具有形状(1,3)和(3,1)的数组? 
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [52]:
#63. 创建一个具有name属性的数组类
class NamedArray(np.ndarray):
     def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
     def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [53]:
#64. 考虑一个给定的向量，如何对由第二个向量索引的每个元素加1(小心重复的索引)?
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[ 1.  2.  2.  5.  2.  5.  5.  3.  3.  2.]


In [54]:
#65. 根据索引列表(I)，如何将向量(X)的元素累加到数组(F)?
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.]


In [55]:
#66. 考虑一个(dtype=ubyte) 的 (w,h,3)图像，计算其唯一颜色的数量
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


In [56]:
#67. 考虑一个四维数组，如何一次性计算出最后两个轴(axis)的和？
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print (sum)

[[49 48 47 72]
 [40 48 57 45]
 [63 52 87 55]]


In [57]:
#68. 考虑一个一维向量D，如何使用相同大小的向量S来计算D子集的均值？
import pandas as pd
print(pd.Series(D).groupby(S).mean())

Exception: Data must be 1-dimensional

In [58]:
#69. 如何获得点积 dot prodcut的对角线? 
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
# slow version
np.diag(np.dot(A, B))

array([ 0.58923302,  1.02652837,  1.45712194,  2.10446148,  0.92897146])

In [59]:
#70. 考虑一个向量[1,2,3,4,5],如何建立一个新的向量，在这个新向量中每个值之间有3个连续的零？
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


In [60]:
#71. 考虑一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘？
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print (A * B[:,:,None])

[[[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]
  [ 2.  2.  2.]]]


In [61]:
#72. 如何对一个数组中任意两行做交换? 
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [62]:
#73. 考虑一个可以描述10个三角形的triplets，找到可以分割全部三角形的line segment
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 2,  8) ( 2, 72) ( 6, 22) ( 6, 53) ( 8, 72) ( 9, 40) ( 9, 95) (13, 60)
 (13, 70) (16, 29) (16, 68) (22, 53) (26, 49) (26, 73) (28, 47) (28, 68)
 (29, 68) (32, 33) (32, 60) (33, 60) (35, 37) (35, 57) (37, 57) (40, 95)
 (47, 68) (49, 73) (60, 70) (74, 74) (74, 98)]


In [63]:
#74. 给定一个二进制的数组C，如何产生一个数组A满足np.bincount(A)==C
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


In [64]:
#75. 如何通过滑动窗口计算一个数组的平均数?
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.]


In [65]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [66]:
#77. 如何对布尔值取反，或者原位(in-place)改变浮点数的符号(sign)？
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)


array([1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0])

In [67]:
#78. 考虑两组点集P0和P1去描述一组线(二维)和一个点p,如何计算点p到每一条线 i (P0[i],P1[i])的距离？
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print (distance(P0, P1, p))

[  7.19129334   8.73683766   8.32479931   6.80654915   0.93153621
   3.41277356   8.32577263  11.35631647   8.29505381  11.2704358 ]


In [70]:
#79.考虑两组点集P0和P1去描述一组线(二维)和一组点集P，如何计算每一个点 j(P[j]) 到每一条线 i (P0[i],P1[i])的距离？
#based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[  9.39189837  10.98200784  13.15018785  15.85467841  13.42704022
    3.50061189   5.57859515   2.80926019   0.84527762  12.33408812]
 [  0.71015467   7.01765317   0.26478766   1.38845421   6.28338305
    4.55023404   5.966654    12.24359266  14.46189014   1.88322583]
 [  7.31520617   6.18087048  13.37057832  11.06434725   2.39998363
    7.54179015   7.83098793   1.52740519   0.85654308  11.61602173]
 [  0.45067699   2.30627267  15.83137389  15.73427257   6.01256316
    4.4597636    9.33616233   2.01601374   1.71102772  14.50664004]
 [  9.98390054   6.34224576  17.99197987  15.15562896   1.49544463
   11.92111951  12.5599638    6.30135845   3.74869535  16.16703367]
 [  7.0823408   12.74196168   1.27987426   1.6688375   11.22667589
    0.49437544   3.71608625   9.28977773  12.99894597   0.67117331]
 [  8.12311626   4.57352872   4.09257545   5.88178967   5.43316976
    7.83706975   2.89532933  10.55515136   9.96171753   3.04787879]
 [  1.1956605    1.80298815  11.90884465  12.07563197  

In [71]:
#80.Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) 
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[3 5 3 7 4 8 5 2 1 4]
 [3 4 3 5 7 9 8 7 1 7]
 [6 5 0 6 3 8 0 9 1 0]
 [0 9 8 2 1 3 7 9 6 5]
 [8 9 6 8 0 6 1 9 3 7]
 [6 8 9 5 8 5 3 0 5 9]
 [1 4 4 5 2 9 4 4 4 1]
 [1 1 0 3 7 5 1 6 5 0]
 [7 5 0 6 7 8 7 8 6 2]
 [5 2 1 1 2 0 8 0 6 2]]
[[0 0 0 0 0]
 [0 3 5 3 7]
 [0 3 4 3 5]
 [0 6 5 0 6]
 [0 0 9 8 2]]


In [72]:
#81. 考虑一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],如何生成一个数组R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]? 
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [73]:
#82. 计算一个矩阵的秩(★★★)
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


In [74]:
#83. 如何找到一个数组中出现频率最高的值？
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

8


In [75]:
#84. 从一个10x10的矩阵中提取出连续的3x3区块
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[1 3 2]
   [0 1 1]
   [4 0 2]]

  [[3 2 4]
   [1 1 3]
   [0 2 3]]

  [[2 4 0]
   [1 3 2]
   [2 3 4]]

  [[4 0 3]
   [3 2 2]
   [3 4 2]]

  [[0 3 0]
   [2 2 2]
   [4 2 3]]

  [[3 0 2]
   [2 2 3]
   [2 3 4]]

  [[0 2 0]
   [2 3 2]
   [3 4 3]]

  [[2 0 4]
   [3 2 2]
   [4 3 0]]]


 [[[0 1 1]
   [4 0 2]
   [1 0 4]]

  [[1 1 3]
   [0 2 3]
   [0 4 4]]

  [[1 3 2]
   [2 3 4]
   [4 4 4]]

  [[3 2 2]
   [3 4 2]
   [4 4 2]]

  [[2 2 2]
   [4 2 3]
   [4 2 0]]

  [[2 2 3]
   [2 3 4]
   [2 0 2]]

  [[2 3 2]
   [3 4 3]
   [0 2 4]]

  [[3 2 2]
   [4 3 0]
   [2 4 3]]]


 [[[4 0 2]
   [1 0 4]
   [0 1 3]]

  [[0 2 3]
   [0 4 4]
   [1 3 1]]

  [[2 3 4]
   [4 4 4]
   [3 1 2]]

  [[3 4 2]
   [4 4 2]
   [1 2 3]]

  [[4 2 3]
   [4 2 0]
   [2 3 1]]

  [[2 3 4]
   [2 0 2]
   [3 1 4]]

  [[3 4 3]
   [0 2 4]
   [1 4 1]]

  [[4 3 0]
   [2 4 3]
   [4 1 2]]]


 [[[1 0 4]
   [0 1 3]
   [4 4 2]]

  [[0 4 4]
   [1 3 1]
   [4 2 0]]

  [[4 4 4]
   [3 1 2]
   [2 0 3]]

  [[4 4 2]
   [1 2 3]
   [0 3 2]]

  [[4 2 0]
   

In [76]:
#85. 创建一个满足 Z[i,j] == Z[j,i]的子类
class Symetric(np.ndarray):
     def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 9  4 18  6  3]
 [ 4  8 17  3 11]
 [18 17  9 42 13]
 [ 6  3 42  6  9]
 [ 3 11 13  9  3]]


In [80]:
#86. 考虑p个 nxn 矩阵和一组形状为(n,1)的向量，如何直接计算p个矩阵的乘积(n,1)？
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)
#It works, because:
M is (p,n,n)
V is (p,n,1)
#Thus, summing over the paired axes 0 and 0 (of M and V independently),
#and 2 and 1, to remain with a (n,1) vector.

[[ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]
 [ 200.]]


False

In [81]:
#87. 对于一个16x16的数组，如何得到一个区域(block-sum)的和(区域大小为4x4)? 
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]]


In [86]:
#88. 如何利用numpy数组实现Game of Life? 
def iterate(Z):
    # Count neighbours
     N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
          Z[1:-1,0:-2]                + Z[1:-1,2:] +
          Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

     # Apply rules
     birth = (N==3) & (Z[1:-1,1:-1]==0)
     survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
     Z[...] = 0
     Z[1:-1,1:-1][birth | survive] = 1
     return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
  1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1
  1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 1 1 0 1 1 0 0 0 0 1 0 0 0
  0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  0 1 0 0 0 0 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0

In [87]:
#89. 如何找到一个数组的第n个最大值?
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [88]:
#90. 给定任意个数向量，创建笛卡尔积(每一个元素的每一种组合)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [89]:
#91. 如何从一个正常数组创建记录数组(record array)? 
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print (R)

[(b'Hello',  2.5, 3) (b'World',  3.6, 2)]


In [90]:
#92. 考虑一个大向量Z, 用三种不同的方法计算它的立方
x = np.random.rand()
np.power(x,3)

0.69290270437573953

In [91]:
#92. 考虑一个大向量Z, 用三种不同的方法计算它的立方
x*x*x

0.6929027043757395

In [92]:
# 方法3
np.einsum('i,i,i->i',x,x,x)

ValueError: einstein sum subscripts string contains too many subscripts for operand 0

In [93]:
#93. 考虑两个形状分别为(8,3) 和(2,2)的数组A和B. 如何在数组A中找到满足包含B中元素的行？(不考虑B中每行元素顺序)？
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[0 1 2 3 4 5 7]


In [94]:
#94. 考虑一个10x3的矩阵，分解出有不全相同值的行 (如 [2,2,3]) 
Z = np.random.randint(0,5,(10,3))
print (Z)

# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)

[[2 3 3]
 [0 0 1]
 [1 0 3]
 [0 4 2]
 [0 2 0]
 [3 3 0]
 [1 3 4]
 [2 3 1]
 [3 1 0]
 [4 4 3]]
[[2 3 3]
 [0 0 1]
 [1 0 3]
 [0 4 2]
 [0 2 0]
 [3 3 0]
 [1 3 4]
 [2 3 1]
 [3 1 0]
 [4 4 3]]


In [95]:
#95. 将一个整数向量转换为matrix binary的表现形式
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [96]:
#96. 给定一个二维数组，如何提取出唯一的(unique)行?
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 0 0]
 [0 0 1]
 [1 0 0]
 [1 1 1]]


In [97]:
#97. 考虑两个向量A和B，写出用einsum等式对应的inner, outer, sum, mul函数
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))# np.sum(A)

sum
6.08191643166


In [98]:
#98. 考虑一个由两个向量描述的路径(X,Y)，如何用等距样例(equidistant samples)对其进行采样(sample)?
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [99]:
#99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[ 2.  0.  1.  1.]]


In [100]:
#100. 对于一个一维数组X，计算它boostrapped之后的95%置信区间的平均值。
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.26869628  0.15202195]
