In [3]:
import pandas as pd
import numpy as np

In [2]:
from pandas import Series,DataFrame

In [3]:
obj=pd.Series([4,7,-5,3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2=pd.Series([4,7,-5,3],index=['d','b','a','c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

-5

In [11]:
obj2['b']

7

In [12]:
obj2[['c','a','d']]

c    3
a   -5
d    4
dtype: int64

In [14]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [15]:
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [17]:

np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [18]:
'b' in obj2

True

In [19]:
'e' in obj2

False

In [20]:
sdata={'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}

In [21]:
obj3=pd.Series(sdata)

In [22]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [23]:
states=['California','Ohio','Oregon','Texas']

In [24]:
obj4=pd.Series(sdata,index=states)

In [25]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [26]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [31]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [32]:
obj4.isnull

<bound method Series.isnull of California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64>

In [33]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [34]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [35]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [36]:
obj4.name='population'

In [37]:
obj4.index.name='state'

In [38]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [39]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [40]:
obj.index=['Bob','Steve','Jeff','ryan']

In [41]:
obj

Bob      4
Steve    7
Jeff    -5
ryan     3
dtype: int64

In [44]:
data={'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
      'year':[2000,2001,2002,2001,2002,2003],
      'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame=pd.DataFrame(data)

In [46]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [47]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [53]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [54]:
frame2=pd.DataFrame(data,columns=['year','state','pop','debt'],
                   ....: index=['one','two','three','four','five','six'])

In [55]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [56]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [57]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [58]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [59]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [60]:
frame2['debt']=16.5

In [61]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [62]:
frame2['debt']=np.arange(6.)

In [63]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [66]:
val=pd.Series([-1.2,-1.5,-1.7], index=['two','four','five'])

In [67]:
frame2['debt']=val

In [68]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [69]:
frame2['eastern']=frame2.state=='Ohio'

In [70]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [71]:
del frame2['eastern']

In [72]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [74]:
pop = {'Nevada':{2001:2.4,2002:2.9},
....:   'Ohio': {2000:1.5,2001:1.7,2002:3.6}}

In [75]:
frame3=pd.DataFrame(pop)

In [76]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [77]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [78]:
pd.DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [79]:
pdata={'Ohio':frame3['Ohio'][:-1],
      ....: 'Nevada':frame3['Nevada'][:2]}

In [80]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [81]:
frame3.index.name='year';frame3.columns.name='state'

In [82]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [83]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [84]:
obj=pd.Series(range(3),index=['a','b','c'])

In [85]:
index=obj.index

In [86]:
index

Index(['a', 'b', 'c'], dtype='object')

In [93]:
index[1:]

Index(['b', 'c'], dtype='object')

In [94]:
labels=pd.Index(np.arange(3))

In [95]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [97]:
obj2=pd.Series([1.5,-2.5,0],index=labels)

In [98]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [99]:
obj2.index is labels

True

In [100]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [101]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [102]:
'Ohio' in frame3.columns

True

In [103]:
2003 in frame3.index

False

In [104]:
dup_labels=pd.Index(['foo','foo','bar','bar'])

In [105]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [106]:
obj=pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])

In [107]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [109]:
obj2=obj.reindex(['a','b','c','d','e'])

In [110]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [111]:
obj3=pd.Series(['blue','purple','yellow'],index=[0,2,4])

In [112]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [113]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [114]:
frame=pd.DataFrame(np.arange(9).reshape((3,3)),
                   ....:  index=['a','c','d'],
                   ....:  columns=['Ohio','Texas','California'])

In [115]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [116]:
frame2=frame.reindex(['a','b','c','d'])

In [117]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [118]:
states=['Texas','Utah','California']

In [119]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [120]:
obj=pd.Series(np.arange(5.),index=['a','b','c','d','e'])

In [121]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [122]:
new_obj=obj.drop('c')

In [123]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [124]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [127]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
                 ....: index=['Ohio','Coloorado','Utah','New York'],
                 ....: columns=['one','two','three','four'])

In [128]:
data

one  two  three  four
Ohio         0    1      2     3
Coloorado    4    5      6     7
Utah         8    9     10    11
New York    12   13     14    15

In [129]:
data.drop(['Colorado','Ohio'])

KeyError: "['Colorado'] not found in axis"

In [130]:
data.drop('two',axis=1)

one  three  four
Ohio         0      2     3
Coloorado    4      6     7
Utah         8     10    11
New York    12     14    15

In [131]:
data.drop(['two','four'],axis='columns')

one  three
Ohio         0      2
Coloorado    4      6
Utah         8     10
New York    12     14

In [132]:
obj.drop('c',inplace=True)

In [133]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [134]:
obj=pd.Series(np.arange(4.),index=['a','b','c','d'])

In [135]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [136]:
obj['b']

1.0

In [137]:
obj[1]

1.0

In [138]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [139]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [140]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [141]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [142]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [143]:
obj['b':'c']=5

In [144]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [146]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
                 ....: index=['Ohio','Colorado','Utah','New York'],
                 ....: columns=['ones','two','three','four'])

In [147]:
data

ones  two  three  four
Ohio         0    1      2     3
Colorado     4    5      6     7
Utah         8    9     10    11
New York    12   13     14    15

In [148]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [149]:
data[['three','one']]

KeyError: "['one'] not in index"

In [150]:
data[:2]

ones  two  three  four
Ohio         0    1      2     3
Colorado     4    5      6     7

In [151]:
data[data['three']>5]

ones  two  three  four
Colorado     4    5      6     7
Utah         8    9     10    11
New York    12   13     14    15

In [152]:
data<5

ones    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [153]:
data[data<5]=0

In [154]:
data

ones  two  three  four
Ohio         0    0      0     0
Colorado     0    5      6     7
Utah         8    9     10    11
New York    12   13     14    15

In [155]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [156]:
data.iloc[2,[3,0,1]]

four    11
ones     8
two      9
Name: Utah, dtype: int32

In [157]:
data.iloc[2]

ones      8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [158]:
data.iloc[[1,2],[3,0,1]]

four  ones  two
Colorado     7     0    5
Utah        11     8    9

In [159]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [160]:
data.iloc[:,:3][data.three>5]

ones  two  three
Colorado     0    5      6
Utah         8    9     10
New York    12   13     14

In [166]:
ser=pd.Series(np.arange(3.))
ser
ser[-1]
ser

KeyError: -1

In [167]:
ser2=pd.Series(np.arange(3.),index=['a','b','c'])

In [168]:
ser2[-1]

2.0

In [169]:
ser2[:1]

a    0.0
dtype: float64

In [170]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [171]:
ser.iloc[:1]

0    0.0
dtype: float64

In [173]:
s1=pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])

In [177]:
s2=pd.Series([-2.1,3.6,-1.5,4,3.1],
             ....: index=['a','c','e','f','g'])

In [175]:
s1

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [178]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [179]:
s1+s2

a   -4.2
c    7.2
e   -3.0
f    8.0
g    6.2
dtype: float64

In [197]:
df1=pd.DataFrame(np.arange(9.).reshape((3,3)),
columns=list('bcd'),     index=['Ohio','Texas','Colorado'])

In [200]:
df2=pd.DataFrame(np.arange(12.).reshape((4,3)),
            columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [201]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [202]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [203]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [204]:
pd.DataFrame({'A':[1,2]})

A
0  1
1  2

In [205]:
pd.DataFrame({'B':[3,4]})

B
0  3
1  4

In [206]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [207]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [208]:
df1-df2

b   c    d   e
Colorado  NaN NaN  NaN NaN
Ohio     -3.0 NaN -2.0 NaN
Oregon    NaN NaN  NaN NaN
Texas    -3.0 NaN -2.0 NaN
Utah      NaN NaN  NaN NaN

In [209]:
df1=pd.DataFrame(np.arange(12.).reshape((3,4)),
columns=list('abcd'))

In [210]:
df2=pd.DataFrame(np.arange(20.).reshape((4,5)),
columns=list('abcde'))

In [211]:
df2.loc[1,'b']=np.nan

In [212]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [213]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [214]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [215]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [216]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [217]:
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [218]:
arr=np.arange(12.).reshape((3,4))

In [219]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [220]:
arr[0]

array([0., 1., 2., 3.])

In [221]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [226]:
frame=pd.DataFrame(np.arange(12.).reshape(4,3)),
columns=list('bde')
index=['Utah','Ohio','Texas','Oregon']

In [227]:
series=frame.iloc[0]

AttributeError: 'tuple' object has no attribute 'iloc'

In [228]:
frame

(     0     1     2
 0  0.0   1.0   2.0
 1  3.0   4.0   5.0
 2  6.0   7.0   8.0
 3  9.0  10.0  11.0,)

In [229]:
series

NameError: name 'series' is not defined

In [4]:
data=pd.DataFrame(np.arange(6).reshape((2,3)),index=pd.Index(['Ohio','Colorado'],name='state'),columns=pd.Index(['one','two','three'],name='number'))

In [5]:
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [6]:
result=data.stack()

In [7]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [8]:
result.unstack

<bound method Series.unstack of state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32>

In [9]:
result.unstack(0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [10]:
result.unstack('state')

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [11]:
s1=pd.Series([0,1,2,3],index=['a','b','c','d'])

In [12]:
s2=pd.Series([4,5,6],index=['c','d','e'])

In [13]:
data2=pd.concat([s1,s2],keys=['one','two'])

In [14]:
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [15]:
data2.unstack()

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [16]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [18]:
data2.unstack().stack(dropna=False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64

In [19]:
df=pd.DataFrame({'left':result,'right':result+5},columns=pd.Index(['left','right'],name='side'))

In [20]:
df

side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [21]:
df.unstack('state')

side   left          right         
state  Ohio Colorado  Ohio Colorado
number                             
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [27]:
data=pd.read_csv('macrodata.csv')

In [28]:
data.head()

year  quarter   realgdp  realcons  realinv  realgovt  realdpi    cpi  \
0  1959        1  2710.349    1707.4  286.898   470.045   1886.9  28.98   
1  1959        2  2778.801    1733.7  310.859   481.301   1919.7  29.15   
2  1959        3  2775.488    1751.8  289.226   491.260   1916.4  29.35   
3  1959        4  2785.204    1753.7  299.356   484.052   1931.3  29.37   
4  1960        1  2847.699    1770.5  331.722   462.199   1955.5  29.54   

      m1  tbilrate  unemp      pop  infl  realint  
0  139.7      2.82    5.8  177.146  0.00     0.00  
1  141.7      3.08    5.1  177.830  2.34     0.74  
2  140.5      3.82    5.3  178.657  2.74     1.09  
3  140.0      4.33    5.6  179.386  0.27     4.06  
4  139.6      3.50    5.2  180.007  2.31     1.19

In [29]:
data.loc['Colorado',['two','three']]

KeyError: 'the label [Colorado] is not in the [index]'

In [31]:
data.iloc[2,[3,0,1]]

realcons    1751.8
year        1959.0
quarter        3.0
Name: 2, dtype: float64

In [32]:
obj=pd.Series(range(4),index=['d','a','b','c'])

In [33]:
obj.sort_index

<bound method Series.sort_index of d    0
a    1
b    2
c    3
dtype: int64>

In [36]:
obj=pd.Series([4,7,-3,2])

In [37]:
obj=pd.Series(range(5),index=['a','a','b','b','c'])

In [38]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [39]:
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=['a','b','c','d'],columns=['one','two'])

In [40]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [41]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [42]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64